In [30]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
d = 181229
dflist = [181222,181215,181208, 181201, 181124,181117]

In [32]:
df = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_'+str(d)+'.txt')

for d in dflist:
    df_new = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_'+str(d)+'.txt')
    df = pd.concat([df,df_new])

In [33]:
df.shape

(1401105, 11)

In [34]:
#df = pd.read_csv('turnstile_181103.csv')
#df = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_'+str(d)+'.txt')

In [35]:
df.columns

Index(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES',
       'EXITS                                                               '],
      dtype='object')

In [36]:
df.columns = ['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES','EXITS']

In [37]:
df.dtypes

C/A         object
UNIT        object
SCP         object
STATION     object
LINENAME    object
DIVISION    object
DATE        object
TIME        object
DESC        object
ENTRIES      int64
EXITS        int64
dtype: object

In [38]:
df.head(3)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,03:00:00,REGULAR,6881995,2333630
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,07:00:00,REGULAR,6882006,2333643
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,11:00:00,REGULAR,6882062,2333740

In [39]:
df['STATION'].nunique()

377

In [40]:
df.groupby('STATION').head(3)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,03:00:00,REGULAR,6881995,2333630
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,07:00:00,REGULAR,6882006,2333643
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,11:00:00,REGULAR,6882062,2333740
504,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/22/2018,01:00:00,REGULAR,3665922,6279000
505,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/22/2018,03:23:00,REGULAR,3665942,6279010
506,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/22/2018,05:00:00,REGULAR,3665946,6279012
1100,A010,R080,00-00-00,57 ST-7 AV,NQRW,BMT,12/22/2018,03:00:00,REGULAR,3954316,1883405
1101,A010,R080,00-00-00,57 ST-7 AV,NQRW,BMT,12/22/2018,11:00:00,REGULAR,3954520,1883680
1102,A010,R080,00-00-00,57 ST-7 AV,NQRW,BMT,12/22/2018,15:00:00,REGULAR,3954970,1884001
1690,A013,R081,01-00-00,49 ST,NQRW,BMT,12/22/2018,03:00:00,REGULAR,5981538,36616823
1691,A013,R081,01-00-00,49 ST,NQRW,BMT,12/22/2018,07:00:00,REGULAR,5981545,36616920
1692,A013,R081,01-00-00,49 ST,NQRW,BMT,12/22/2018,11:00:00,REGULAR,5981561,36617262
2620,A021,R032,01-00-00,TIMES SQ-42 ST,ACENQRS1237W,BMT,12/22/2018,03:00:00,REGULAR,8418018,10254353
2621,A021,R032,01-00-00,TIMES SQ-42 ST,ACENQRS1237W,BMT,12/22/2018,07:00:00,REGULAR,8418071,10254422
2622,A021,R032,01-00-00,TIMES SQ-42 ST,ACENQRS1237W,BMT,12/22/2018,11:00:00,REGULAR,8418245,10254855
2956,A022,R022,01-00-00,34 ST-HERALD SQ,BDFMNQRW,BMT,12/22/2018,03:00:00,REGULAR,26278245,10828102
2957,A022,R022,01-00-00,34 ST-HERALD SQ,BDFMNQRW,BMT,12/22/2018,07:00:00,REGULAR,26278286,10828142
2958,A022,R022,01-00-00,34 ST-HERALD SQ,BDFMNQRW,BMT,12/22/2018,11:00:00,REGULAR,26278527,10828427
3596,A027,R082,01-00-00,28 ST,NRW,BMT,12/22/2018,03:00:00,REGULAR,3274892,3923330
3597,A027,R082,01-00-00,28 ST,NRW,BMT,12/22/2018,07:00:00,REGULAR,3274903,3923369
3598,A027,R082,01-00-00,28 ST,NRW,BMT,12/22/2018,11:00:00,REGULAR,3274979,3923604
3974,A030,R083,01-00-00,23 ST,NRW,BMT,12/22/2018,03:00:00,REGULAR,6980617,4488653
3975,A030,R083,01-00-00,23 ST,NRW,BMT,12/22/2018,07:00:00,REGULAR,6980628,4488681
3976,A030,R083,01-00-00,23 ST,NRW,BMT,12/22/2018,11:00:00,REGULAR,6980682,4488823
4578,A033,R170,02-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/22/2018,00:00:00,REGULAR,2052605,5166456
4579,A033,R170,02-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/22/2018,04:00:00,REGULAR,2052620,5166475
4580,A033,R170,02-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/22/2018,08:00:00,REGULAR,2052625,5166524
5674,A038,R085,00-00-00,8 ST-NYU,NRW,BMT,12/22/2018,03:00:00,REGULAR,3447169,2962413
5675,A038,R085,00-00-00,8 ST-NYU,NRW,BMT,12/22/2018,07:00:00,REGULAR,3447194,2962437
5676,A038,R085,00-00-00,8 ST-NYU,NRW,BMT,12/22/2018,11:00:00,REGULAR,3447238,2962584
...,...,...,...,...,...,...,...,...,...,...,...
197375,R641,R210,00-00-00,BEVERLY RD,25,IRT,12/22/2018,03:00:00,REGULAR,9611642,4373856
197376,R641,R210,00-00-00,BEVERLY RD,25,IRT,12/22/2018,07:00:00,REGULAR,9611744,4373862
197377,R641,R210,00-00-00,BEVERLY RD,25,IRT,12/22/2018,11:00:00,REGULAR,9611967,4373896
197537,R643,R135,00-00-00,NEWKIRK AV,25,IRT,12/22/2018,00:00:00,REGULAR,13669497,1171232
197538,R643,R135,00-00-00,NEWKIRK AV,25,IRT,12/22/2018,04:00:00,REGULAR,13669551,1171241
197539,R643,R135,00-00-00,NEWKIRK AV,25,IRT,12/22/2018,08:00:00,REGULAR,13669799,1171253
197915,R645,R110,00-00-00,FLATBUSH AV-B.C,25,IRT,12/22/2018,00:00:00,REGULAR,11798852,13572050
197916,R645,R110,00-00-00,FLATBUSH AV-B.C,25,IRT,12/22/2018,04:00:00,REGULAR,11798875,13572128
197917,R645,R110,00-00-00,FLATBUSH AV-B.C,25,IRT,12/22/2018,08:00:00,REGULAR,11798971,13572159
198755,R726,R329,00-00-00,MORRIS PARK,5,IRT,12/22/2018,00:00:00,REGULAR,928074,3350699
198756,R726,R329,00-00-00,MORRIS PARK,5,IRT,12/22/2018,04:00:00,REGULAR,928075,3350772
198757,R726,R329,00-00-00,MORRIS PARK,5,IRT,12/22/2018,08:00:00,REGULAR,928094,3350795
199175,R729,R292,00-00-00,BAYCHESTER AV,5,IRT,12/22/2018,00:00:00,REGULAR,1208767,396467
199176,R729,R292,00-00-00,BAYCHESTER AV,5,IRT,12/22/2018,04:00:00,REGULAR,1208772,396476
199177,R729,R292,00-00-00,BAYCHESTER AV,5,IRT,12/22/2018,08:00:00,REGULAR,1208816,396491
199301,R730,R431,00-00-00,EASTCHSTER/DYRE,5,IRT,12/22/2018,00:00:00,REGULAR,1528541,2917934
199302,R730,R431,00-00-00,EASTCHSTER/DYRE,5,IRT,12/22/2018,04:00:00,REGULAR,1528541,2917940
199303,R730,R431,00-00-00,EASTCHSTER/DYRE,5,IRT,12/22/2018,08:00:00,REGULAR,1528551,2917955
199511,S101,R070,00-00-00,ST. GEORGE,1,SRT,12/22/2018,03:00:00,REGULAR,1317176,231
199512,S101,R070,00-00-00,ST. GEORGE,1,SRT,12/22/2018,07:00:00,REGULAR,1317198,231
199513,S101,R070,00-00-00,ST. GEORGE,1,SRT,12/22/2018,11:00:00,REGULAR,1317250,231
200616,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,12/22/2018,01:00:00,REGULAR,568204,12
200617,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,12/22/2018,05:00:00,REGULAR,568207,12
200618,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,12/22/2018,09:00:00,REGULAR,568246,12
200910,TRAM2,R469,00-00-00,RIT-ROOSEVELT,R,RIT,12/22/2018,00:00:00,REGULAR,4099,64
200911,TRAM2,R469,00-00-00,RIT-ROOSEVELT,R,RIT,12/22/2018,04:00:00,REGULAR,4117,66
200912,TRAM2,R469,00-00-00,RIT-ROOSEVELT,R,RIT,12/22/2018,08:00:00,REGULAR,4134,67
200593,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,12/15/2018,00:00:00,REGULAR,222730,4169
200594,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,12/15/2018,04:00:00,REGULAR,222788,4170
200595,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,12/15/2018,08:00:00,REGULAR,222810,4170

In [41]:
#df.groupby('STATION','DATE').head(3)
df.groupby(['STATION','DATE']).head(3)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,03:00:00,REGULAR,6881995,2333630
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,07:00:00,REGULAR,6882006,2333643
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/22/2018,11:00:00,REGULAR,6882062,2333740
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/23/2018,03:00:00,REGULAR,6882830,2333933
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/23/2018,07:00:00,REGULAR,6882834,2333939
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/23/2018,11:00:00,REGULAR,6882878,2333982
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/24/2018,03:00:00,REGULAR,6883470,2334101
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/24/2018,07:00:00,REGULAR,6883478,2334131
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/24/2018,11:00:00,REGULAR,6883541,2334266
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/25/2018,03:00:00,REGULAR,6884397,2334394
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/25/2018,07:00:00,REGULAR,6884401,2334398
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/25/2018,11:00:00,REGULAR,6884422,2334430
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/26/2018,03:00:00,REGULAR,6884633,2334514
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/26/2018,07:00:00,REGULAR,6884639,2334549
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/26/2018,11:00:00,REGULAR,6884735,2334753
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/27/2018,03:00:00,REGULAR,6886041,2334913
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/27/2018,07:00:00,REGULAR,6886060,2334958
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/27/2018,11:00:00,REGULAR,6886168,2335217
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/28/2018,03:00:00,REGULAR,6887698,2335419
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/28/2018,07:00:00,REGULAR,6887713,2335473
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/28/2018,11:00:00,REGULAR,6887826,2335738
504,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/22/2018,01:00:00,REGULAR,3665922,6279000
505,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/22/2018,03:23:00,REGULAR,3665942,6279010
506,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/22/2018,05:00:00,REGULAR,3665946,6279012
511,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/23/2018,01:00:00,REGULAR,3667091,6280855
512,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/23/2018,05:00:00,REGULAR,3667113,6280862
513,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/23/2018,09:00:00,REGULAR,3667131,6280979
517,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/24/2018,01:00:00,REGULAR,3668168,6282422
518,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/24/2018,05:00:00,REGULAR,3668187,6282430
519,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/24/2018,09:00:00,REGULAR,3668223,6282852
...,...,...,...,...,...,...,...,...,...,...,...
197975,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/14/2018,01:00:00,REGULAR,562338,12
197976,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/14/2018,05:00:00,REGULAR,562340,12
197977,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/14/2018,09:00:00,REGULAR,562394,12
197983,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/15/2018,01:00:00,REGULAR,562549,12
197984,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/15/2018,05:00:00,REGULAR,562553,12
197985,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/15/2018,09:00:00,REGULAR,562603,12
197989,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/16/2018,01:00:00,REGULAR,562731,12
197990,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/16/2018,05:00:00,REGULAR,562734,12
197991,S102,R165,00-00-00,TOMPKINSVILLE,1,SRT,11/16/2018,09:00:00,REGULAR,562778,12
198259,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/10/2018,00:00:00,REGULAR,184307,3448
198260,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/10/2018,04:00:00,REGULAR,184335,3454
198261,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/10/2018,08:00:00,REGULAR,184356,3454
198265,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/11/2018,00:00:00,REGULAR,185674,3472
198266,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/11/2018,04:00:00,REGULAR,185698,3473
198267,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/11/2018,08:00:00,REGULAR,185712,3473
198271,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/12/2018,00:00:00,REGULAR,186846,3503
198272,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/12/2018,04:00:00,REGULAR,186855,3503
198273,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/12/2018,08:00:00,REGULAR,186869,3505
198277,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/13/2018,00:00:00,REGULAR,188021,3527
198278,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/13/2018,04:00:00,REGULAR,188026,3529
198279,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/13/2018,08:00:00,REGULAR,188044,3533
198283,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/14/2018,00:00:00,REGULAR,188816,3548
198284,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/14/2018,04:00:00,REGULAR,188822,3551
198285,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/14/2018,08:00:00,REGULAR,188855,3552
198289,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/15/2018,00:00:00,REGULAR,189727,3570
198290,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/15/2018,04:00:00,REGULAR,189738,3570
198291,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/15/2018,08:00:00,REGULAR,189755,3573
198295,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/16/2018,00:00:00,REGULAR,190408,3589
198296,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/16/2018,04:00:00,REGULAR,190423,3591
198297,TRAM1,R468,00-00-00,RIT-MANHATTAN,R,RIT,11/16/2018,08:00:00,REGULAR,190437,3591

In [42]:
df.groupby('STATION').ENTRIES.mean()

STATION
1 AV               3.041629e+08
103 ST             1.045375e+07
103 ST-CORONA      7.617098e+06
104 ST             5.352100e+08
110 ST             6.039903e+06
111 ST             7.807155e+06
116 ST             8.222878e+07
116 ST-COLUMBIA    2.038177e+08
121 ST             1.176147e+08
125 ST             8.856409e+07
135 ST             1.090539e+07
137 ST CITY COL    2.510434e+07
138/GRAND CONC     3.330449e+08
14 ST              1.143744e+08
14 ST-UNION SQ     2.174820e+07
145 ST             4.991540e+07
149/GRAND CONC     3.172782e+07
14TH STREET        3.606907e+05
15 ST-PROSPECT     1.143071e+07
155 ST             4.636599e+06
157 ST             5.044288e+06
161/YANKEE STAD    5.732638e+07
163 ST-AMSTERDM    2.325911e+06
167 ST             9.197830e+06
168 ST             7.432698e+06
169 ST             1.887389e+06
170 ST             8.294034e+07
174 ST             1.187017e+08
174-175 STS        2.109334e+06
175 ST             2.366072e+07
                       ...
SUTTER AV          1.408922e+06
SUTTER AV-RUTLD    2.975434e+06
THIRTY ST          3.767967e+05
THIRTY THIRD ST    7.758627e+05
TIMES SQ-42 ST     1.164621e+08
TOMPKINSVILLE      3.163023e+05
TREMONT AV         2.602301e+07
TWENTY THIRD ST    5.779362e+05
UNION ST           4.268217e+06
UTICA AV           1.573458e+07
V.CORTLANDT PK     1.603145e+08
VAN SICLEN AV      4.191465e+06
VAN SICLEN AVE     4.342354e+06
VERNON-JACKSON     3.482495e+06
W 4 ST-WASH SQ     1.265723e+07
W 8 ST-AQUARIUM    1.644835e+06
WAKEFIELD/241      4.167214e+06
WALL ST            1.290928e+07
WEST FARMS SQ      4.894170e+07
WESTCHESTER SQ     9.561873e+06
WHITEHALL S-FRY    1.845104e+07
WHITLOCK AV        1.308345e+06
WILSON AV          3.690792e+06
WINTHROP ST        6.767629e+06
WOODHAVEN BLVD     5.185633e+06
WOODLAWN           5.902181e+06
WORLD TRADE CTR    8.882731e+07
WTC-CORTLANDT      2.083504e+07
YORK ST            1.358743e+07
ZEREGA AV          3.935508e+06
Name: ENTRIES, Length: 377, dtype: float64

In [43]:
df.columns

Index(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES', 'EXITS'],
      dtype='object')

In [44]:
df.groupby('STATION').EXITS.mean()

STATION
1 AV               1.629392e+08
103 ST             4.058605e+07
103 ST-CORONA      7.737579e+06
104 ST             3.886944e+08
110 ST             5.828021e+06
111 ST             4.178979e+06
116 ST             1.040372e+08
116 ST-COLUMBIA    4.378295e+07
121 ST             3.232789e+07
125 ST             5.023673e+07
135 ST             2.084540e+06
137 ST CITY COL    8.843532e+07
138/GRAND CONC     3.215476e+08
14 ST              8.054032e+07
14 ST-UNION SQ     8.014325e+06
145 ST             1.047965e+08
149/GRAND CONC     1.453856e+06
14TH STREET        1.903950e+05
15 ST-PROSPECT     6.035457e+05
155 ST             3.448118e+06
157 ST             3.174478e+06
161/YANKEE STAD    3.710631e+07
163 ST-AMSTERDM    1.246344e+06
167 ST             7.196646e+06
168 ST             3.662230e+06
169 ST             1.226191e+06
170 ST             1.014029e+08
174 ST             5.321003e+07
174-175 STS        9.683288e+05
175 ST             1.919599e+07
                       ...
SUTTER AV          9.234742e+05
SUTTER AV-RUTLD    2.405636e+06
THIRTY ST          3.098901e+05
THIRTY THIRD ST    6.261306e+05
TIMES SQ-42 ST     9.114914e+07
TOMPKINSVILLE      9.997422e+03
TREMONT AV         2.004704e+07
TWENTY THIRD ST    4.024630e+05
UNION ST           4.278954e+06
UTICA AV           4.287611e+06
V.CORTLANDT PK     1.570284e+08
VAN SICLEN AV      3.662858e+06
VAN SICLEN AVE     4.429995e+06
VERNON-JACKSON     2.402909e+06
W 4 ST-WASH SQ     5.832633e+06
W 8 ST-AQUARIUM    1.717920e+06
WAKEFIELD/241      4.308639e+06
WALL ST            7.771271e+06
WEST FARMS SQ      8.025515e+06
WESTCHESTER SQ     8.828433e+06
WHITEHALL S-FRY    4.810241e+06
WHITLOCK AV        9.945321e+05
WILSON AV          3.323809e+06
WINTHROP ST        1.471013e+06
WOODHAVEN BLVD     2.326286e+06
WOODLAWN           2.335622e+06
WORLD TRADE CTR    1.023798e+08
WTC-CORTLANDT      2.006745e+04
YORK ST            1.117894e+07
ZEREGA AV          1.942636e+05
Name: EXITS, Length: 377, dtype: float64

In [45]:
df.groupby(['STATION','DATE']).EXITS.mean()

STATION    DATE
1 AV       11/10/2018    1.628469e+08
           11/11/2018    1.628469e+08
           11/12/2018    1.628477e+08
           11/13/2018    1.628497e+08
           11/14/2018    1.628520e+08
           11/15/2018    1.628544e+08
           11/16/2018    1.628569e+08
           11/17/2018    1.628582e+08
           11/18/2018    1.628582e+08
           11/19/2018    1.628592e+08
           11/20/2018    1.571410e+08
           11/21/2018    1.628635e+08
           11/22/2018    1.628650e+08
           11/23/2018    1.628661e+08
           11/24/2018    1.628673e+08
           11/25/2018    1.628685e+08
           11/26/2018    1.696308e+08
           11/27/2018    1.628724e+08
           11/28/2018    1.628746e+08
           11/29/2018    1.628770e+08
           11/30/2018    1.628794e+08
           12/01/2018    1.628816e+08
           12/02/2018    1.628832e+08
           12/03/2018    1.628850e+08
           12/04/2018    1.628873e+08
           12/05/2018    1.628896e+08
           12/06/2018    1.628920e+08
           12/07/2018    1.628945e+08
           12/08/2018    1.628968e+08
           12/09/2018    1.628987e+08
                             ...
ZEREGA AV  11/29/2018    3.298114e+05
           11/30/2018    1.746052e+05
           12/01/2018    9.713883e+04
           12/02/2018    9.734192e+04
           12/03/2018    9.759681e+04
           12/04/2018    9.803969e+04
           12/05/2018    9.848900e+04
           12/06/2018    9.893828e+04
           12/07/2018    1.058241e+05
           12/08/2018    9.827867e+04
           12/09/2018    9.848886e+04
           12/10/2018    9.847550e+04
           12/11/2018    9.876625e+04
           12/12/2018    9.919261e+04
           12/13/2018    9.963136e+04
           12/14/2018    1.000562e+05
           12/15/2018    1.004170e+05
           12/16/2018    1.006443e+05
           12/17/2018    9.794639e+04
           12/18/2018    1.013333e+05
           12/19/2018    1.017812e+05
           12/20/2018    1.022291e+05
           12/21/2018    1.026622e+05
           12/22/2018    1.030089e+05
           12/23/2018    1.032328e+05
           12/24/2018    1.034577e+05
           12/25/2018    1.024534e+05
           12/26/2018    1.014241e+05
           12/27/2018    1.017555e+05
           12/28/2018    1.044384e+05
Name: EXITS, Length: 18340, dtype: float64